Add explicit linking to `atomic` library when required
tomopy/PTL pull request #1
Opened 2023-11-01 14:48 UTC by csparker247

This PR checks if the compiler provides `std::atomic` as an external library and links PTL libraries against it if required. This is essentially an update of @LocutusOfBorg's changes for PTLv3.

2023-11-01 16:03 UTC, csparker247 commented
I've tested that this still builds fine on my M1 MBP. 

I also want to draw attention here to [this comment](https://github.com/tomopy/tomopy/issues/628#issuecomment-1782494105). In short, the original intent of this was to support riscv64 on gcc when gcc didn't provide atomic. Since the original contribution, gcc has added native support for atomic on riscv64, so these changes aren't strictly necessary for that platform, but may be useful for others.

2023-11-01 16:09 UTC, csparker247 commented
I also meant to ask, do you want to open a PR to the upstream from `tomopy/PTL`, or should I just go ahead and open it myself?

2023-11-03 15:56 UTC, carterbox requested changes
Thanks for opening this PR. I think these changes are still necessary if downstream users only have access to version of GCC before they added atomics support.

Please address errors from the upstream CI checks that I just activated.

2023-11-03 15:56 UTC, carterbox commented on cmake/Modules/CheckAtomic.cmake
> +  set(HAVE_CXX_ATOMICS_WITHOUT_LIB True)
Why do we just skip directly to setting this variable for MSVC and APPLE? Isn't the point of this test to actually check if the code snips above compile?

2023-11-03 17:19 UTC, csparker247 commented on cmake/Modules/CheckAtomic.cmake
> +  set(HAVE_CXX_ATOMICS_WITHOUT_LIB True)
That's a good question. It was part of the original commits, and I can at least confirm that removing `APPLE` there breaks my build. But the really the compiler check should handle that, I would think. I'll look closer at the rest of the module logic.

2023-11-06 11:39 UTC, csparker247 commented on cmake/Modules/CheckAtomic.cmake
> +  set(HAVE_CXX_ATOMICS_WITHOUT_LIB True)
I need to lint my latest changes, but I've refactored CheckAtomic in a way that should be more generic across platforms.

2023-11-06 11:50 UTC, csparker247 commented on cmake/Modules/CheckAtomic.cmake
> +include(CheckLibraryExists)
```suggestion
```

2023-11-07 21:36 UTC, merged